name: IASO CI Test (JS)
description: IASO CI Test Action (JS)

inputs:
    branch:
        description: The branch to test
        required: true
        default: develop

outputs:
    time:
        description: The time it took to test

runs:
    using: 'node20'
    main: dist/index.js