name: Deploy IASO docker
run-name: Deploy docker image ${{ inputs.image_tag }} to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      iaso_branch:
        description: IASO branch to deploy (docker compose, cron)
        required: true
        type: string
      plugin_branch:
        description: Plugin branch to deploy (docker compose extensions)
        required: false
        type: string
        default: ''
      plugin_name:
        description: Plugin name
        required: false
        type: string
        default: ''
      environment:
        description: playground, staging, demo or prod for worker and web or exact Env name like iaso-stg-worker. Using `upgrade` for now to test
        required: true
        type: string
      image_tag:
        description: Tag to deploy (without the "blsq/iaso:" prefix, e.g. "develop", "IA-4856", or "v2026.06.01")
        required: true
        type: string
      slack_channel:
        description: Slack Channel for notification (iasops by default)
        required: false
        default: cloud-alerts
        type: string

permissions:
  contents: read
  packages: read

jobs:
  config:
    runs-on: ubuntu-24.04
    outputs:
      slack_channel: ${{ steps.vars.outputs.slack_channel }}
      short_sha: ${{ steps.vars.outputs.short_sha }}
      repo: ${{ steps.repo.outputs.repo }}
    steps:
      - name: Received parameters
        run: |
          echo "IASO branch: ${{ inputs.iaso_branch }}"
          echo "Plugin branch: ${{ inputs.plugin_branch }}"
          echo "Plugin name: ${{ inputs.plugin_name }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Image tag: ${{ inputs.image_tag }}"
          echo "Slack channel: ${{ inputs.slack_channel }}"

      - name: Set configs
        id: vars
        env:
          DEFAULT_SLACK_CHANNEL: cloud-alerts
        run: |
          echo "slack_channel=${{ github.event.inputs.slack_channel || env.DEFAULT_SLACK_CHANNEL }}" >> $GITHUB_OUTPUT
          if [ -n "$GITHUB_SHA" ]; then
            echo "short_sha=${GITHUB_SHA:0:12}" >> $GITHUB_OUTPUT
          else
            echo "short_sha=manual-$(openssl rand -hex 3)" >> $GITHUB_OUTPUT
          fi

      - name: Determine image repo
        id: repo
        run: |
          if [ -n "${{ inputs.plugin_branch }}" ] && [ -n "${{ inputs.plugin_name }}" ]; then
            echo "repo=${{ inputs.plugin_name }}" >> $GITHUB_OUTPUT
           elif [ -z "${{ inputs.plugin_branch }}" ] && [ -z "${{ inputs.plugin_name }}" ]; then
            echo "repo=iaso" >> $GITHUB_OUTPUT
          else
            echo "::error::Both inputs.plugin_branch and inputs.plugin_name must be provided together"
            exit 1
          fi

  check_image:
    needs: config
    runs-on: ubuntu-24.04
    outputs:
      image_digest: ${{ steps.image_data.outputs.image_digest }}
      image_timestamp: ${{ steps.image_data.outputs.image_timestamp }}
    steps:
#      - name: Check if image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} exists on Docker Hub
#        run: |
#          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
#            "https://hub.docker.com/v2/repositories/blsq/${{ needs.config.outputs.repo }}/tags/${{ inputs.image_tag }}")
#          if [ "$STATUS" != "200" ]; then
#            echo "::error::Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} not found on Docker Hub"
#            exit 1
#          fi
#          echo "Image blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} found"
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the image and inspect it to get the digest and timestamp
        id: image_data
        run: |
#          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }}
          echo "image_digest=$(docker image inspect blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} --format='{{index .RepoDigests 0}}' | cut -d ':' -f2)" >> $GITHUB_OUTPUT
          echo "image_timestamp=$(docker image inspect blsq/${{ needs.config.outputs.repo }}:${{ inputs.image_tag }} --format='{{ index .Created }}')" >> $GITHUB_OUTPUT

  deploy:
    needs: [ config, check_image ]
    runs-on: ubuntu-24.04
    env:
      MSG_MINIMAL: true
      SLACK_CHANNEL: ${{ needs.config.outputs.slack_channel }}
      SLACK_ICON_EMOJI: ":robot_face:"
      SLACK_USERNAME: ${{ inputs.environment }}
      SLACK_WEBHOOK: ${{ secrets.TEST_SLACK_WEBHOOK }}
      SLACK_MESSAGE: ${{  format('<https://github.com/{0}/commit/{1}/checks|🔗{2} logs> | <https://github.com/{0}/commit/{1}/checks|🔗 Commit {1}>', github.repository, github.sha, github.job) }}
      SLACK_FOOTER: "-"

    steps:
      - name: Slack deployment start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ""
          SLACK_TITLE: Started deployment of ${{ inputs.image_tag }} on ${{ inputs.environment }} ...

      - name: Deploying ${{ inputs.image_tag }} to ${{ inputs.environment }}, using branch ${{ inputs.iaso_branch }}
        run: |
          echo "
           ___    _    ____   ___
          |_ _|  / \  / ___| / _ \\
           | |  / _ \ \___ \| | | |
           | | / ___ \ ___) | |_| |
          |___/_/   \_\____/ \___/
          ------------------------
          Deploying ${{ inputs.image_tag }} to ${{ inputs.environment }}, using branch ${{ inputs.iaso_branch }} - plugin branch ${{ inputs.plugin_branch }}
          $(date)
          "

      - name: Checkout IASO code
        uses: actions/checkout@v6
        with:
          repository: 'BLSQ/iaso'
          ref: ${{ inputs.iaso_branch }}

      - name: Checkout plugin code
        if: inputs.plugin_branch != ''
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.plugin_branch }}
          path: plugins/${{ inputs.plugin_name }}

      - name: Verify layout
        if: inputs.plugin_branch != ''
        run: |
          ls -las
          ls -las plugins
          ls -las plugins/${{ inputs.plugin_name }}

      - name: Fetch IASO docker compose file
        if : inputs.plugin_branch == ''
        run: mv docker/prod/docker-compose.prod.yml deployment/docker-compose.yml

      - name: Fetch IASO and plugin docker compose files
        if : inputs.plugin_branch != ''
        run: docker compose -f docker/prod/docker-compose.prod.yml -f plugins/${{ inputs.plugin_name }}/docker-compose.prod.yml config --no-interpolate --no-path-resolution --no-normalize > deployment/docker-compose.yml

      - name: Fetch cron.yaml file
        run: mv cron.yaml deployment/cron.yaml

      - name: Set env vars in beanstalk config
        run: |
          sed -i s/deployed_by_value/${GITHUB_ACTOR}/g ./deployment/.ebextensions/environment.config
          sed -i "s/deployed_on_value/$(date --rfc-3339=seconds)/g" ./deployment/.ebextensions/environment.config
          sed -i s/prod_image_digest_value/${{ needs.check_image.outputs.image_digest }}/g ./deployment/.ebextensions/environment.config
          sed -i s/prod_image_creation_value/${{ needs.check_image.outputs.image_timestamp }}/g ./deployment/.ebextensions/environment.config
          sed -i s/prod_image_tag_value/${{ inputs.image_tag }}/g ./deployment/.ebextensions/environment.config
          sed -i s/plugin_env_1_value/plugin_1/g ./deployment/.ebextensions/environment.config
          sed -i s/plugin_env_2_value/plugin_2/g ./deployment/.ebextensions/environment.config
          sed -i s/plugin_env_3_value/plugin_3/g ./deployment/.ebextensions/environment.config
          cat ./deployment/.ebextensions/environment.config

      - name: Install Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
          cache-suffix: deploy

      - name: Install deployment dependencies
        run: |
          uv sync --only-group deploy --locked
          echo "UV_NO_SYNC=1" >> $GITHUB_ENV

      - name: Environment info
        run: uv tree --only-group deploy

      - name: Determine EBS version name
        id: version
        run: |
          echo "VERSION_NAME=${{ inputs.image_tag }}-${{ needs.config.outputs.short_sha }}" >> $GITHUB_OUTPUT

      - name: Deploy to beanstalk (Docker) using scripts/eb_deploy.py
        run: |
          cd deployment
          git add .
          git status
          uv run python ../scripts/eb_deploy.py ${{ inputs.environment }} docker
        env:
          # VERSION_NAME is the ID of the package generated by EBS that's gonna be deployed. It needs to be unique, otherwise an old package will be reployed
          VERSION_NAME: ${{ steps.version.outputs.VERSION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Slack deployment success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Iaso ${{ inputs.image_tag }} successfully deployed on ${{ inputs.environment }}
        if: success()

      - name: Slack deployment failure notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Deployment failure Iaso ${{ inputs.image_tag }} - ${{ inputs.environment }}
        if: failure()
